# === Paths ===
image_root: './Ma_Culture_Images'         # dossier contenant tes sous-dossiers d'images
ann_root: './annotation'                  # dossier où se trouve le fichier .json
train_file: ['train_maroc.json']    # ton fichier d’annotations

# === Model ===
pretrained: 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_capfilt_large.pth'
vit: 'base'

# === Hyperparameters ===
batch_size: 16              # Ajouter la clé batch_size ici
batch_size_train: 16
batch_size_test: 32
vit_grad_ckpt: False
vit_ckpt_layer: 0
init_lr: 2e-5
min_lr: 0
weight_decay: 0.05
max_epoch: 10

# === Training Image Settings ===
image_size: 384

# === Inference (optional) ===
k_test: 128
inference: 'rank'

# === Prompt (ajouter ici) ===
prompt: "Une description des images marocaines pour l'entraînement."
